fix bluetooth feature
haobtc/python-trezor pull request #5
Opened 2020-03-02 10:02 UTC by liyanhrxy

2020-03-02 10:30 UTC, danielsocials commented on src/trezorlib/transport/udp.py
> +    DEFAULT_HOST = "192.168.1.110"
这个不应该改

2020-03-02 10:32 UTC, danielsocials commented on src/trezorlib/transport/protocol.py
> +        print(f"====send in ble===={bytes(buffer).hex()}")
用log 替换print

2020-03-02 10:33 UTC, danielsocials commented on src/trezorlib/transport/protocol.py
> +    """Protocol version 1. Currently (11/2018) in use on all Trezor.
这个改错了吧

2020-03-02 10:33 UTC, danielsocials commented on src/trezorlib/transport/nfc.py
> +        # if not NFCHandle.device:
删除

2020-03-02 11:28 UTC, shuaiLiWang commented on src/trezorlib/client.py
> +            self._raw_write(messages.Cancel())
修改一下_raw_write接口 是不是直接return self._raw_write(messages.Cancel())比较好

2020-03-02 11:28 UTC, shuaiLiWang commented on src/trezorlib/client.py
> +import time
没用到

2020-03-02 11:42 UTC, shuaiLiWang commented on src/trezorlib/transport/bluetooth.py
> +                return new_response
if not cls.RESPONSE 会不会造成cpu高

2020-03-03 03:02 UTC, danielsocials commented on src/trezorlib/transport/protocol.py
> +    """Protocol version 1. Currently (11/2018) in use on all Trezor.
Trezors应该是对的吧

2020-03-03 03:09 UTC, danielsocials requested changes

2020-03-03 03:09 UTC, danielsocials commented on src/trezorlib/btc.py
> +    print("begin sign first")
print to LOG

2020-03-03 03:09 UTC, danielsocials commented on src/trezorlib/btc.py
> +            print("begin sign four")
同上

2020-03-03 03:09 UTC, danielsocials commented on src/trezorlib/btc.py
> +            print("begin sign third")
同上

2020-03-03 03:09 UTC, danielsocials commented on src/trezorlib/btc.py
> +            print("begin sign second")
同上

2020-03-03 03:09 UTC, danielsocials commented on src/trezorlib/client.py
> +    print("------get_transport-------")
同上

2020-03-03 03:09 UTC, danielsocials commented on src/trezorlib/client.py
> +            print(f"====response in ca{resp}=====")
同上

2020-03-03 03:09 UTC, danielsocials commented on src/trezorlib/client.py
> +                print("ack=======")
同上

2020-03-03 03:09 UTC, danielsocials commented on src/trezorlib/client.py
> +                print("end====")
同上

2020-03-03 03:09 UTC, danielsocials commented on src/trezorlib/device.py
> +        print("reset exception")
同上

2020-03-03 03:09 UTC, danielsocials commented on src/trezorlib/transport/bluetooth.py
> +# from cn.com.heaton.blelibrary.ble.callback import BleWriteCallback
删除

2020-03-03 03:09 UTC, danielsocials commented on src/trezorlib/transport/bluetooth.py
> +        # self.BLE.writeQueue(RequestTask.newWriteTask(self.BLE_ADDRESS, chunks))
删除

2020-03-03 03:09 UTC, danielsocials commented on src/trezorlib/transport/bluetooth.py
> +    """
删除或者添加内容

2020-03-03 03:09 UTC, danielsocials commented on src/trezorlib/transport/protocol.py
> +        # buffer = bytearray(b"##" + header + ser)
删除无用代码

2020-03-03 03:09 UTC, danielsocials commented on src/trezorlib/transport/protocol.py
> +        print(f"send ====={bytes(buffer).hex()}")
print

2020-03-03 03:09 UTC, danielsocials commented on src/trezorlib/transport/protocol.py
> +        print(f"response ===={protobuf.load_message(BytesIO(response[3+headerlen:]), mapping.get_class(msg_type))}")
print

2020-03-03 04:10 UTC, merged